#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("patternSelect() works", {

  expect_error(
    kwb.vs2dh:::patternSelect()
    # argument "data" is missing, with no default
  )

})

