#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convSoils() works", {

  expect_error(
    kwb.vs2dh:::convSoils()
    # argument "conf" is missing, with no default
  )

})

