#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convBasic() works", {

  expect_error(
    kwb.vs2dh:::convBasic()
    # argument "baseConf" is missing, with no default
  )

})

