#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("filterLines() works", {

  expect_error(
    kwb.vs2dh:::filterLines()
    # argument "data" is missing, with no default
  )

})

