#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("importMatrices() works", {

  expect_error(
    kwb.vs2dh:::importMatrices()
    # argument "prepData" is missing, with no default
  )

})

