#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("vs2di.runConfig() works", {

  expect_error(
    kwb.vs2dh:::vs2di.runConfig()
    # argument "conf" is missing, with no default
  )

})

