#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convMatrixByRowToString() works", {

  expect_error(
    kwb.vs2dh:::convMatrixByRowToString()
    # argument "matr" is missing, with no default
  )

})

