#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("nodePairs() works", {

  expect_error(
    kwb.vs2dh:::nodePairs()
    # argument "n" is missing, with no default
  )

})

