#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("vs2dh.writeConfig() works", {

  expect_error(
    kwb.vs2dh:::vs2dh.writeConfig()
    # argument "conf" is missing, with no default
  )

})

