#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convRecharge() works", {

  expect_error(
    kwb.vs2dh:::convRecharge()
    # argument "rechConf" is missing, with no default
  )

})

