#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("prepareImport() works", {

  expect_error(
    kwb.vs2dh:::prepareImport()
    # argument "model.path" is missing, with no default
  )

})

