#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("vs2di.readBalance() works", {

  expect_error(
    kwb.vs2dh:::vs2di.readBalance()
    # argument "engine" is missing, with no default
  )

})

