#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("labeledList() works", {

  expect_error(
    kwb.vs2dh:::labeledList()
    # argument "inpLst" is missing, with no default
  )

})

