#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("vs2di.readMain() works", {

  expect_error(
    kwb.vs2dh:::vs2di.readMain()
    # argument "model.path" is missing, with no default
  )

})

