#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("vs2dh.readVariables() works", {

  expect_error(
    kwb.vs2dh:::vs2dh.readVariables()
    # argument "model.path" is missing, with no default
  )

})

