#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convInitial() works", {

  expect_error(
    kwb.vs2dh:::convInitial()
    # argument "iniConf" is missing, with no default
  )

})

