#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("cutStringByPattern() works", {

  expect_error(
    kwb.vs2dh:::cutStringByPattern()
    # argument "txt" is missing, with no default
  )

})

