#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convertStringVectorToMatrix() works", {

  expect_error(
    kwb.vs2dh:::convertStringVectorToMatrix()
    # argument "values" is missing, with no default
  )

})

