#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("vs2dh.plotMatrix() works", {

  expect_error(
    kwb.vs2dh:::vs2dh.plotMatrix()
    # argument "data" is missing, with no default
  )

})

