#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("splitHeader() works", {

  expect_error(
    kwb.vs2dh:::splitHeader()
    # argument "header" is missing, with no default
  )

})

