#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("convertToWindowsPath() works", {

  expect_error(
    kwb.vs2dh:::convertToWindowsPath()
    # argument "path" is missing, with no default
  )

})

