#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("leafValues() works", {

  expect_error(
    kwb.vs2dh:::leafValues()
    # argument "x" is missing, with no default
  )

})

