#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("vs2dh.plotVariables() works", {

  expect_error(
    kwb.vs2dh:::vs2dh.plotVariables()
    # argument "data" is missing, with no default
  )

})

