#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("importRechargePeriods() works", {

  expect_error(
    kwb.vs2dh:::importRechargePeriods()
    # argument "prepData" is missing, with no default
  )

})

