#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("multipleLineValues() works", {

  expect_error(
    kwb.vs2dh:::multipleLineValues()
    # argument "data" is missing, with no default
  )

})

